#!/bin/bash

# remove directory @ bundle

rm -fr L9
rm -fr ReplaceWithRegister
rm -fr SQHell.vim
rm -fr ZoomWin
rm -fr ansible-vim
rm -fr base16-vim
rm -fr comfortable-motion
rm -fr dbext
rm -fr jellybeans.vim
rm -fr junos.vim
rm -fr plsql.vim
rm -fr plsql.vim-syntax
rm -fr potion
rm -fr ultisnips
rm -fr vim-maketable
rm -fr vim-marked
rm -fr vim-picker
rm -fr vim-ps1
rm -fr vim-sort-motion
rm -fr vim-test
rm -fr vim-translate-me
rm -fr vimux
rm -fr vim-eunuch
rm -fr vim-rake
rm -fr vim-rails
rm -fr vim-system-copy
rm -fr vim-tmux-navigator
rm -fr vim-textobj-entire
rm -fr vim-textobj-line
rm -fr vim-textobj-user
rm -fr vim-textobj-indent
rm -fr vim-textobj-rubyblock
rm -fr vis
rm -fr gundo.vim
rm -fr scratch.vim
rm -fr SQHuserpwd.vim
rm -fr supertab
rm -fr syntastic
rm -fr tabular
rm -fr vim-bundler
rm -fr vimcmdline
rm -fr vim-coffee-script
rm -fr vim-dispatch
rm -fr vim-haml
rm -fr vim-less
rm -fr vimproc.vim
